replicaCount: 1

image:
  repository: soumil22/flask-love-app
  pullPolicy: Always
  tag: latest

service:
  name: flask-love-app
  type: NodePort  # Change to NodePort for easier access
  port: 80
  targetPort: 5000
  nodePort: 30000  # Expose on a specific port, adjust this as needed

resources: {}
